---
title: "Exploring Data Structures in R"
author: "Ken Wood"
date: "10/5/2024"
output:
  pdf_document: default
  html_document: default
---

## Objective

The objective of this assignment is to deepen your understanding of data structures in R by incorporating indexing, updating, and advanced manipulation techniques for vectors, data frames, lists, and matrices.

#### INSTRUCTIONS: 

In your own R script file, please complete the following tasks:

1.	Vectors:

```{r vectors}
# Create a numeric vector named my_vector containing the numbers 1, 3, 5, 7, and 9.
my_vector <- c(1,3,5,7,9)
my_vector

# Extract the third element from my_vector.
my_vector[3]

# Update the second element of my_vector to be twice its original value.
my_vector[2] <- 2*my_vector[2]
my_vector
```

2.	Data Frames:

```{r}
# Create a data frame named student_data with the following columns:
#  Student_ID: Numeric vector with student IDs from 1 to 5.
#  Name: Character vector with the names of five students (you pick which names!).
#  Score: Numeric vector with scores (between 60 and 100) for each student.

student_data <- data.frame(
  Student_ID = c(1,2,3,4,5),
  Name = c('Rocky','Bullwinkle','Larry','Moe','Curly'),
  score = c(65,85,60,70,100)
)
student_data

# Update the score of the student with ID 3 to 95.
student_data$score[student_data$Student_ID == 3] <- 95
student_data
```

3.	Lists:


```{r}

# Create a list named my_list with the following elements:

# - Element 1: A numeric vector containing the numbers 10, 20, 30.
# - Element 2: A character vector containing the names of three countries.
# - Element 3: A data frame with two columns - City (character vector) and Population (numeric vector) - for three cities of your choice.

my_list <- list(c(10,20,30),c('USA','Canada','Mexico'),
                data.frame(City = c('Washington DC','Ottawa','Mexico City'),
                Population = c(689545,1017449,9209944)))
my_list

# Access and print the second element of the character vector within my_list.

my_list[[2]][2]
```

4.	Matrices:

```{r}
# Create a 3x3 matrix named my_matrix with random numeric values.
my_matrix <- matrix(runif(9), nrow = 3, ncol = 3)
my_matrix

# Extract the last column of my_matrix.
my_matrix[,3]
```









